# Generated by Django 3.1.7 on 2021-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0002_produitcoquillages_produitcrustaces_produitpoissons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tig_id', models.IntegerField(default='-1')),
                ('category', models.IntegerField(default='-1')),
                ('price', models.FloatField(default='0')),
            ],
            options={
                'ordering': ('tig_id',),
            },
        ),
    ]
