# Generated by Django 3.1.7 on 2021-04-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0003_ventes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventes',
            name='dow',
            field=models.FloatField(default='-1'),
        ),
        migrations.AddField(
            model_name='ventes',
            name='mois',
            field=models.FloatField(default='-1'),
        ),
    ]
