# Generated by Django 3.1.7 on 2021-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0004_auto_20210423_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventes',
            options={'ordering': ('year',)},
        ),
        migrations.RemoveField(
            model_name='ventes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ventes',
            name='tig_id',
        ),
        migrations.AddField(
            model_name='ventes',
            name='year',
            field=models.FloatField(default='-1'),
        ),
    ]
