# Generated by Django 3.1.7 on 2021-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0005_auto_20210423_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventes',
            name='day',
            field=models.FloatField(default='-1'),
        ),
    ]
